name: Deploy

on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
  workflow_dispatch:

jobs:
  Terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@master
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: './terraform'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY }}
        #TF_CLI_ARGS: '-var-file="env/dev.tfvars" -backend-config="bucket=${{ secrets.STATE_BUCKET_DEV }}" '

    - name: Terraform Validate
      run: terraform validate 

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: './terraform'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY }}
        #TF_CLI_ARGS: '-var-file="env/dev.tfvars"'