name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  Terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@master
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY }}

    - name: Terraform Validate
      run: terraform validate 

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_TOKEN }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY }}