name: Function Testing
    
on: 
  push:
  
  workflow_run:
    workflows: 
      -Deploy with Terraform
      -Upload to resume.aaronlangley.net S3 bucket
    type:
      - complete

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Endpoint Testing
      - uses: actions/checkout@v1
        shell: bash
        run: |
          chmod +x ./scripts/resumeFunctionTest.sh
          bash ./scripts/resumeFunctionTest.sh
      
