name: Function Testing
    
on: 
  push:
  
  workflow_run:
    workflows: 
      -Deploy with Terraform
      -Upload to resume.aaronlangley.net S3 bucket
    type:
      - complete

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Endpoint Testing
        shell: bash
        run: |
          cd scripts
          chmod +x resumeFunctionTest.sh
          ./resumeFunctionTest.sh
      
