name: Function Testing
    
on: 
  push:
  
  workflow_run:
    workflows: 
      -Deploy with Terraform
      -Upload to resume.aaronlangley.net S3 bucket
    type:
      - complete

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Endpoint Testing
        working-directory: scripts/
        shell: bash
        run: |
          bash resumeFunctionTest.sh
      
